import { useEffect } from "react";
import LegalDocument, { LegalSection } from "@/components/LegalDocument";

const privacySections: LegalSection[] = [
  {
    id: "scope-roles",
    title: "1. Scope & Roles",
    content: [
      "Scope. This Policy applies to our public website, admin console, APIs, and Slack applications (collectively, the \"Services\").",
      "Customer vs. Teammato Roles. Customers (organizations that install our Slack app) act as data controllers for content and metadata originating from their Slack workspace (\"Workspace Data\"). Teammato acts as a data processor/service provider for Workspace Data and as a controller for account, billing, and operational information (\"Account Data\").",
      "No Address. We intentionally do not publish a physical address in this Policy.",
    ],
  },
  {
    id: "definitions",
    title: "2. Definitions",
    content: [
      "\"Personal Data\" means any information that identifies or can reasonably be linked to a particular individual, and includes \"personal information,\" \"personal data,\" and similar terms under applicable law.",
      "\"Workspace Data\" means encrypted content, comments, and related metadata processed through the Services from your Slack workspace.",
      "\"Account Data\" means information tied to your organization's account and billing (e.g., admin names/emails, plan tier, invoices).",
      "\"Service Metadata\" means operational data generated by usage of the Services (e.g., timestamps, event types, counts) that does not contain message content.",
      "\"Subprocessors\" are third parties engaged by Teammato to process Personal Data on our behalf.",
    ],
  },
  {
    id: "information-collect",
    title: "3. Information We Collect",
    content: [
      "3.1 From Customers (Account Data): Admin names and business contact details; Workspace identifiers, plan tier, seat cap, usage counts; Billing contact, tax information, and payment status via our payment processor.",
      "3.2 From Slack (Workspace Data & Limited Profile Data): Encrypted posts and comments created via our Slack workflow or admin console; Minimal Slack profile and audience information to enforce seat caps and audience rules (e.g., user groups, channel membership), excluding message content beyond what users submit to Teammato; Slack app installation and event data necessary to operate the integration.",
      "3.3 Service Metadata (Operational): Event logs comprising content-free analytics (e.g., feature usage counts, success/failure codes); System metrics necessary for security, audit, and performance.",
      "3.4 Cookies & Similar Technologies: Essential cookies and security challenges (e.g., Cloudflare Turnstile) to protect forms and authentication; No third-party advertising cookies are used.",
      "3.5 Do Not Collect Categories: We do not intentionally collect sensitive identifiers (government IDs, full payment card numbers), protected class information, or precise geolocation through the Services. We do not use or enable microphone, camera, or device sensors.",
    ],
  },
  {
    id: "privacy-by-design",
    title: "4. Our Privacy-by-Design Commitments",
    content: [
      "Plaintext Never Stored. We process user submissions and persist them as ciphertext only. No plaintext message content is stored in databases or logs. Encryption is mandatory—the system hard-fails if the master key is unavailable.",
      "Strong Encryption at Rest. Workspace Data is encrypted at rest using per-organization 256-bit data encryption keys (DEKs) with XChaCha20-Poly1305 AEAD and unique nonces per record. DEKs are generated locally, stored wrapped, and support rotation. All encryption operations are monitored with structured logging for operational visibility.",
      "K-Anonymity with Buffer. All views/exports/digests are k-gated with k=5 minimum. Topics are visible only when participant count reaches k+2 to prevent exact-k attribution. Small cohorts are suppressed by default across UI/exports.",
      "Minimum Population Requirement. Feedback submission requires at least 10 active users in the organization to prevent small-org re-identification attacks.",
      "Differential Privacy. Statistical noise (Laplace distribution, ε=0.5) is added to all exposed participant counts to prevent exact inference while maintaining utility for analytics.",
      "Per-Thread Anonymization. Each feedback thread uses unique, irreversible submitter hashes (not daily rotation) to eliminate cross-topic correlation.",
      "Timing Attack Protection. All notifications (DM receipts, channel posts) are delayed with 5-30 second random jitter to prevent timing-based correlation attacks.",
      "Timestamp Precision Control. All exports round timestamps to day-level precision to prevent timing triangulation.",
      "PII Filtering at Ingestion. Mentions, emails, phone numbers, and Slack IDs are scrubbed before encryption.",
      "Content-Free Analytics. We maintain an append-only, content-free event stream and aggregated counts only; no message text is logged. Slack payloads are scrubbed of user_id, team_id, and channel_id before any logging.",
      "Role- and Row-Level Isolation. We enforce per-organization isolation via database RLS.",
      "Note: Some features may require limited profile/audience reads to enforce seat caps and eligibility. We never write back to Slack content channels on your behalf except as necessary for app operation (e.g., slash command acknowledgments).",
    ],
  },
  {
    id: "data-purposes",
    title: "5. Why We Process Data (Purposes)",
    content: [
      "We process data to: Provide and maintain the Services (including installation, command handling, weekly digests, and admin features); Secure the Services (fraud prevention, abuse detection, rate limiting); Enforce plan limits and seat caps; administer billing and invoicing; Provide customer support and respond to requests; Develop and improve the Services (e.g., measuring funnels and reliability) using content-free analytics; Comply with law, enforce legal terms, and protect rights, property, security, and integrity.",
      "We do not sell Personal Data and we do not engage in cross-context behavioral advertising.",
    ],
  },
  {
    id: "legal-bases",
    title: "6. Legal Bases (EEA/UK/Switzerland)",
    content: [
      "Where GDPR/UK GDPR applies, we rely on one or more of the following legal bases:",
      "Performance of a contract (Art. 6(1)(b)) to provide the Services to customers",
      "Legitimate interests (Art. 6(1)(f)) in securing and improving the Services, provided such interests are not overridden by data subject rights",
      "Compliance with legal obligations (Art. 6(1)(c))",
      "Consent (Art. 6(1)(a)) where required for optional features",
    ],
  },
  {
    id: "sharing",
    title: "7. How We Share Information",
    content: [
      "Service Providers/Subprocessors. We use vetted providers for infrastructure, payments, email delivery, and security. Each provider is bound by confidentiality and data-protection obligations.",
      "Compliance & Safety. We may disclose information to competent authorities where required by law or to protect the rights, safety, or security of users and the public. We require valid legal process and will narrow scope where permitted.",
      "Business Transfers. In connection with a corporate transaction, subject to appropriate safeguards.",
      "We do not share Personal Data with third parties for their independent marketing.",
    ],
  },
  {
    id: "international-transfers",
    title: "8. International Transfers",
    content: [
      "Where data is transferred across borders, we implement appropriate safeguards (e.g., SCCs, DPAs, and technical measures such as per-org encryption and content minimization). Customers may request our DPA and subprocessor list from Trust@teammato.com.",
    ],
  },
  {
    id: "security",
    title: "9. Security Measures",
    content: [
      "Per-org DEKs; XChaCha20-Poly1305 AEAD; unique nonces per record",
      "Key wrapping and rotation support",
      "Structured logs with token/PII redaction; no message text in logs",
      "Network and application security controls; least-privilege access; audit",
      "Legal hold support for retention purges",
      "Ongoing monitoring for webhook/API reliability and error rates",
      "No security program is perfect; however, our layered controls, default anonymization, and content-free logging are designed to significantly reduce risk.",
    ],
  },
  {
    id: "retention",
    title: "10. Data Retention & Deletion",
    content: [
      "Customer-defined retention. Administrators can configure retention periods; data is purged accordingly, subject to legal hold.",
      "Account Data. Retained for the duration of the customer relationship and as required by law (e.g., tax/audit).",
      "Deletion. Upon verified request by an authorized admin or upon account termination, we will delete or irreversibly de-identify Personal Data in accordance with our retention schedule and legal obligations.",
    ],
  },
  {
    id: "slack-integration",
    title: "11. Slack Integration Details",
    content: [
      "Scopes. Minimal scopes to operate the app (e.g., commands, chat:write, and read-only audience scopes for users, user groups, and channels).",
      "Operations. Slash commands are acknowledged within 2 seconds; message content submitted to Teammato is encrypted before storage; we do not store plaintext.",
      "Uninstall Events. We receive uninstall signals to complete data handling obligations.",
    ],
  },
  {
    id: "analytics-cookies",
    title: "12. Analytics & Cookies",
    content: [
      "Analytics. Event-level, content-free telemetry (e.g., counts, success/failure) and daily aggregates; no message content.",
      "Cookies/Turnstile. We use strictly necessary cookies and Cloudflare Turnstile to protect forms and authenticate sessions. We do not use third-party advertising cookies.",
    ],
  },
  {
    id: "billing",
    title: "13. Payments & Billing",
    content: [
      "Payments are processed by our third-party payment provider. We receive limited billing metadata and tax information; we do not store full payment card numbers.",
      "Plan enforcement and seat caps are administered using audience counts and usage thresholds. Read/export access continues even when posting is temporarily blocked due to overage.",
    ],
  },
  {
    id: "children",
    title: "14. Children's Privacy",
    content: [
      "The Services are not directed to children and are intended for organizational use by workplace users. We do not knowingly collect Personal Data from individuals under the age of 16. If you believe a child has provided us Personal Data, contact Contact@teammato.com.",
    ],
  },
  {
    id: "customer-responsibilities",
    title: "15. Customer Responsibilities",
    content: [
      "Configure audience mode and exclusions appropriately and review eligibility counts",
      "Maintain unique admin accounts and safeguard credentials and Slack permissions",
      "Configure retention periods consistent with your legal obligations and internal policies",
      "Provide required notices to end users and obtain any consents that may be necessary under applicable law",
    ],
  },
  {
    id: "privacy-rights",
    title: "16. Your Privacy Rights",
    content: [
      "Depending on your location, you may have rights to access, correct, delete, restrict, or port your Personal Data, and to object to certain processing. You also may have the right to lodge a complaint with a supervisory authority.",
      "How to exercise your rights: If you are an end user of a customer's Slack workspace, please direct your request to your employer (the controller). We will assist the controller as required. If you interact with Teammato directly (e.g., as an admin/billing contact), email Trust@teammato.com with your request. We will verify your identity and respond consistent with applicable laws.",
      "We do not discriminate against individuals for exercising privacy rights.",
    ],
  },
  {
    id: "us-state-notices",
    title: "17. California & U.S. State Notices",
    content: [
      "For residents of California and other U.S. states with privacy laws (e.g., Virginia, Colorado, Connecticut, Utah, Oregon, Texas), we provide the following disclosures:",
      "Categories Collected. Identifiers (admin names/emails), commercial information (plan tier), internet/electronic activity (usage events), and in some cases limited employment-related information necessary for audience calculations.",
      "Sources. Directly from you, from Slack (as configured by your admin), and from our Services.",
      "Business/Commercial Purposes. As described in Section 5.",
      "Sharing/Selling. We do not sell Personal Data and do not share Personal Data for cross-context behavioral advertising.",
      "Sensitive Data. We do not intentionally collect sensitive categories through the Services.",
      "Retention. See Section 10.",
      "Rights. Access, deletion, correction, portability, and opt-out of certain processing as applicable by state law.",
      "Authorized agents may submit requests on your behalf by emailing Trust@teammato.com with documentation establishing authority.",
    ],
  },
  {
    id: "automated-decisions",
    title: "18. Automated Decision-Making",
    content: [
      "We do not engage in automated decision-making that produces legal or similarly significant effects on individuals without human involvement.",
    ],
  },
  {
    id: "international-users",
    title: "19. International Users",
    content: [
      "Where local law requires data localization or additional measures, we will work with customers to implement appropriate contractual and technical safeguards (e.g., SCCs, encryption controls). Please contact Trust@teammato.com to discuss your needs.",
    ],
  },
  {
    id: "dpa-subprocessors",
    title: "20. Data Protection Addendum & Subprocessors",
    content: [
      "We make a DPA available upon request and maintain a current list of Subprocessors used to deliver the Services. Customers may request copies or subscribe to change notifications by emailing Trust@teammato.com.",
    ],
  },
  {
    id: "security-incidents",
    title: "21. Security Incidents & Notification",
    content: [
      "In the event of a confirmed security incident affecting Personal Data, we will notify affected customers without undue delay, provide relevant information as it becomes available, and cooperate to meet legal obligations.",
    ],
  },
  {
    id: "policy-changes",
    title: "22. Changes to This Policy",
    content: [
      "We may update this Policy from time to time to reflect operational or legal changes. We will post the updated Policy with a new Effective Date and, where required, provide more prominent notice or obtain consent.",
    ],
  },
  {
    id: "contact",
    title: "23. Contact Us",
    content: [
      "Trust & Security: Trust@teammato.com",
      "General Inquiries & Privacy Requests: Contact@teammato.com",
    ],
  },
  {
    id: "dispute-resolution",
    title: "24. Dispute Resolution; Governing Law; Arbitration",
    content: [
      "Governing Law. This Policy and any dispute arising out of or relating to it shall be governed by the laws in the state where Teammato LLC is currently incorporated, without regard to conflict-of-laws rules.",
      "Informal Resolution. Before filing a claim, the parties agree to try to resolve the dispute informally for 30 days by emailing Trust@teammato.com.",
      "Arbitration. Any dispute that cannot be resolved informally shall be finally resolved by binding, individual arbitration administered by a reputable arbitration provider under its rules in effect when the claim is filed. The seat and venue shall be in the state where Teammato LLC is currently incorporated. Judgment on the award may be entered in any court of competent jurisdiction.",
      "Class-Action Waiver. To the fullest extent permitted by law, disputes must be brought on an individual basis and not as a class, consolidated, or representative action.",
      "Injunctive Relief. Notwithstanding the foregoing, either party may seek temporary or preliminary injunctive relief in any court of competent jurisdiction to protect its rights pending arbitration.",
    ],
  },
  {
    id: "additional-notices",
    title: "25. Additional Notices & Disclaimers",
    content: [
      "No Regulated Data. The Services are not designed for PHI (HIPAA), PCI-DSS primary account numbers, or other regulated data requiring specialized handling. Do not submit such data.",
      "Third-Party Links. Where our Services link to third-party sites/services, their privacy practices govern.",
      "Conflicts. If there is a conflict between this Policy and an executed DPA, the DPA controls for processing activities in scope.",
    ],
  },
  {
    id: "key-controls",
    title: "26. Summary of Key Controls (Non-Exhaustive)",
    content: [
      "Plaintext never stored; encrypted content columns only",
      "Per-org DEKs with rotation; unique nonces per record",
      "K-anonymity (k=5) for views, exports, and digests; small-n hidden",
      "PII filtered at ingestion; token/PII redacted from logs",
      "Content-free analytics and aggregated counts; no message text in logs",
      "Customer-configurable retention with legal-hold support",
      "Least-privilege Slack scopes; read-only audience syncing",
      "Admin export excludes ciphertext; includes k-safe summaries and metadata",
      "For questions about this Policy or our security posture, contact Trust@teammato.com.",
    ],
  },
];

export default function Privacy() {
  useEffect(() => {
    document.title = "Privacy Policy — Teammato";
  }, []);

  return (
    <LegalDocument
      title="Teammato Privacy Policy"
      effectiveDate="October 6, 2025"
      introduction='Teammato, LLC ("Teammato," "we," "us," or "our") provides Slack-first, privacy-focused tools for anonymous feedback and weekly digests for teams. This Privacy Policy explains what information we collect, how we use and share it, your choices and rights, and our security and compliance commitments. This Policy is designed to be comprehensive and protective of liability for a SaaS offering focused on anonymity and security. If you are an enterprise customer and require a negotiated Data Processing Addendum ("DPA"), please contact Trust@teammato.com.'
      sections={privacySections}
      downloadFilename="teammato-privacy-policy.txt"
    />
  );
}
