import LegalDocument, { LegalSection } from "@/components/LegalDocument";

const termsSections: LegalSection[] = [
  {
    id: "definitions",
    title: "1. Key Definitions",
    content: [
      '"Account" means a customer organization\'s account with Teammato.',
      '"Admin" means a User designated by Customer to configure the Services and manage the Account.',
      '"Affiliate" means any entity that controls, is controlled by, or is under common control with a party.',
      '"Anonymized Output" means aggregated programmatic outputs (e.g., weekly digests, trends, charts) that do not disclose individual User identities and that adhere to k-anonymity thresholds.',
      '"Authorized Use" means use of the Services in accordance with this Agreement, Documentation, and applicable law.',
      '"Confidential Information" has the meaning in Section 14.',
      '"Customer" means the organization that owns the Slack workspace into which the Services are installed and that enters into this Agreement.',
      '"Customer Content" means any information, text, data, or other material submitted to or through the Services by or on behalf of Customer or its Users, including content sent through Slack workflows to Teammato. For clarity, Customer Content may include Personal Data of Users.',
      '"Documentation" means Teammato\'s user guides, help content, policies, and specifications for the Services.',
      '"Order" means an online sign-up, checkout, or other ordering document (including any Admin console plan selection) specifying the Services purchased by Customer.',
      '"Personal Data" means information that identifies or is reasonably linkable to an individual.',
      '"Service Data" means operational data generated by the Services (e.g., logs, event counts, performance metrics) that does not include message text content of Customer Content.',
      '"Subprocessor" means a third party engaged by Teammato to process Personal Data on Teammato\'s behalf.',
      '"User" means an individual who is authorized by Customer to use the Services under Customer\'s Account (e.g., employees, contractors, and Admins) and who interacts via Slack or the admin console.',
    ],
  },
  {
    id: "eligibility-accounts",
    title: "2. Eligibility; Accounts; Admin Authority",
    content: [
      "2.1 Eligibility. You must be at least the age of majority in your jurisdiction and authorized by Customer to use the Services. The Services are designed for organizational use, not for personal/consumer use by minors.",
      "2.2 Account Creation. Customer must provide accurate Account information and keep it current. Customer is responsible for Users' activity and for maintaining the confidentiality of any credentials.",
      "2.3 Admin Authority. Admins can configure features, manage Users, set retention periods, export summaries, and initiate deletion requests. Teammato will act on instructions reasonably appearing to be from an Admin.",
      "2.4 Free Trials and Beta Features. We may offer free trials or Beta features. Beta features are provided AS IS, may be suspended at any time, and may be subject to additional terms.",
    ],
  },
  {
    id: "slack-integration",
    title: "3. Slack Integration; Operation of the Services",
    content: [
      "3.1 Slack Authorization. The Services require installation and authorization within a Slack workspace controlled by Customer. Customer is responsible for maintaining Slack permissions and complying with Slack's terms.",
      "3.2 Minimum Scopes; Least Privilege. We request only the scopes necessary to operate the Services (e.g., slash commands, minimal read for audience eligibility counts, chat:write for acknowledgments). We do not store plaintext message content.",
      "3.3 Anonymous Submissions. Customer Content submitted through Teammato workflows is encrypted and processed to preserve anonymity. Views/exports are subject to k-anonymity gating (default k=5) so that small-n cohorts are suppressed by design.",
      "3.4 Service Data and Telemetry. We maintain content-free telemetry (counts, success/failure codes) for reliability and improvement. No message text is stored in logs.",
      "3.5 Retention and Deletion. Admins may configure retention. Upon verified Admin request or termination, we delete or de-identify Customer Content consistent with Section 12.",
    ],
  },
  {
    id: "licenses-content",
    title: "4. Licenses; Customer Content; Anonymized Output",
    content: [
      "4.1 Customer Content Ownership. As between the parties, Customer retains all right, title, and interest in Customer Content.",
      "4.2 Customer License to Teammato. Customer grants Teammato a non-exclusive, worldwide, royalty-free license to host, process, transmit, encrypt, and display Customer Content as necessary to provide the Services to Customer, and to generate Anonymized Output.",
      "4.3 Anonymized Output. Teammato may generate and use Anonymized Output for Customer's internal use, and may use anonymized, aggregated statistics to maintain and improve the Services. Teammato will not re-identify Anonymized Output.",
      "4.4 Responsibility for Customer Content. Customer is solely responsible for Customer Content and represents that it has all rights necessary to submit it and to grant the license above. Customer will not submit regulated data that the Services are not designed to handle (see Section 9.6).",
    ],
  },
  {
    id: "acceptable-use",
    title: "5. Acceptable Use; Prohibited Conduct",
    content: [
      "Customer and Users will not, and will not permit anyone to:",
      "Violate laws or rights of others; submit content that is illegal, harassing, defamatory, infringing, or invasive of privacy.",
      "Circumvent or attempt to defeat anonymity safeguards (e.g., re-identification of posters, triangulation of small cohorts).",
      "Reverse engineer, decompile, or otherwise attempt to extract source code, except to the extent such restrictions are prohibited by law.",
      "Interfere with or disrupt the Services or related systems.",
      "Use the Services to collect or process: Protected health information (PHI) under HIPAA; Full payment card numbers or bank account numbers; Government-issued ID numbers; Precise geolocation or biometric identifiers; Any data subject to export control restrictions without authorization.",
      "Misrepresent identity or affiliation, or perform unauthorized vulnerability scans or penetration testing.",
      "We may suspend or terminate access for violations (Section 17).",
    ],
  },
  {
    id: "intellectual-property",
    title: "6. Teammato IP; Feedback; Marks",
    content: [
      "6.1 Reservation of Rights. Except for the limited rights expressly granted, Teammato and its licensors retain all rights in the Services, including software, Documentation, and Service Data.",
      "6.2 Feedback. If you provide suggestions or feedback, you grant Teammato a perpetual, irrevocable, worldwide, royalty-free license to use the feedback without restriction or obligation.",
      "6.3 Marks. Customer grants us a limited, revocable right to display Customer's name and logo solely to indicate that Customer uses the Services, unless Customer opts out by emailing Contact@teammato.com. We will comply with reasonable brand guidelines provided in writing.",
    ],
  },
  {
    id: "billing",
    title: "7. Subscriptions; Billing; Taxes; Overage",
    content: [
      "7.1 Plans. Services are offered by subscription as described in the Order (plan tier, term, seat cap). Unless otherwise specified, subscriptions automatically renew for successive terms equal to the expiring term.",
      "7.2 Fees and Payment. Customer will pay fees via our payment processor in the currency shown at checkout. Fees are non-refundable and exclusive of taxes, which Customer is responsible for. Late amounts may incur reasonable late charges or interest as permitted by law.",
      "7.3 Seat Caps and Audience Rules. Seat caps and audience eligibility are enforced programmatically (e.g., by user groups or channel membership). If over the cap, posting may be temporarily blocked while read/export access continues. Customer remains responsible for fees associated with actual use.",
      "7.4 Changes and Upgrades. Admins may upgrade plans or add capacity in the admin console; prorated fees may apply.",
      "7.5 Trials and Promotions. Any free or promotional offers are at Teammato's discretion and may be modified or withdrawn.",
    ],
  },
  {
    id: "privacy-security",
    title: "8. Privacy; Security; Data Processing",
    content: [
      "8.1 Privacy Policy. Our processing of Personal Data is described in the Privacy Policy.",
      "8.2 Security. We implement technical and organizational measures designed to protect Customer Content, including per-organization encryption keys and k-anonymity gating. No system is perfectly secure, and Customer is responsible for User access management within Slack and the admin console.",
      "8.3 DPA. Where required by law, we will enter into a DPA with Customer upon request. Our Subprocessors are subject to appropriate contractual obligations.",
      "8.4 Incident Response. Upon confirmation of a Security Incident affecting Personal Data, we will notify Customer without undue delay and provide information reasonably available to assist Customer in meeting legal obligations.",
    ],
  },
  {
    id: "service-commitments",
    title: "9. Service Commitments and Limitations",
    content: [
      "9.1 Availability. We strive for high availability and reliability. Scheduled maintenance and emergency downtime may occur.",
      "9.2 Support. Admins may contact support via Contact@teammato.com. Enterprise support terms, if any, will be set out in the Order.",
      "9.3 No Professional Advice. The Services provide tools and summaries; they do not constitute legal, HR, or other professional advice. Customer is responsible for internal policies and compliance.",
      "9.4 Third-Party Services. The Services interoperate with Slack and other third-party services. We are not responsible for third-party services, their availability, or changes to their features, terms, or APIs.",
      "9.5 Beta and Experimental Features. Beta features may be incomplete, inaccurate, or unavailable and are provided without warranties.",
      "9.6 No Regulated Data. The Services are not designed for PHI, PCI primary account numbers, or other highly regulated data categories. Customer agrees not to submit such data.",
    ],
  },
  {
    id: "export-controls",
    title: "10. Export Controls; Sanctions",
    content: [
      "Customer represents and warrants that it (and its Users) are not located in, under the control of, or a national or resident of any embargoed country or prohibited party list and will not use the Services for purposes prohibited by export control or sanctions laws.",
    ],
  },
  {
    id: "open-source",
    title: "11. Open Source Components",
    content: [
      "The Services may include open source components subject to their own licenses. To the extent required by the applicable license, those terms will govern over these Terms with respect to the open source components.",
    ],
  },
  {
    id: "data-retention",
    title: "12. Data Retention; Deletion; Return of Data",
    content: [
      "12.1 Retention. Customer may set retention parameters in the admin console. We may retain limited Account records as required by law (e.g., tax/audit).",
      "12.2 Deletion. Upon verified Admin request or termination, we will delete or irreversibly de-identify Customer Content in accordance with our retention schedule and applicable law.",
      "12.3 Exports. Admins may export k-safe summaries and metadata. For security and anonymity, exports do not contain plaintext message content.",
    ],
  },
  {
    id: "warranties",
    title: "13. Warranties; Disclaimers",
    content: [
      "13.1 Mutual Authority. Each party represents and warrants that it has the right and authority to enter into this Agreement.",
      "13.2 Teammato Warranty. We warrant that the Services will materially conform to the Documentation during a paid subscription. Customer's exclusive remedy for breach is re-performance of the Services or, if we cannot cure, termination with a pro-rata refund of prepaid, unused fees for the affected portion of the term.",
      "13.3 Disclaimers. EXCEPT AS EXPRESSLY STATED, THE SERVICES AND ALL RELATED MATERIALS ARE PROVIDED \"AS IS\" AND \"AS AVAILABLE,\" WITHOUT WARRANTIES OF ANY KIND, WHETHER EXPRESS, IMPLIED, STATUTORY, OR OTHERWISE, INCLUDING WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, TITLE, AND NON-INFRINGEMENT, AND ANY WARRANTIES ARISING FROM COURSE OF DEALING OR USAGE OF TRADE. WE DO NOT WARRANT THAT THE SERVICES WILL BE UNINTERRUPTED OR ERROR-FREE OR MEET CUSTOMER'S REQUIREMENTS.",
    ],
  },
  {
    id: "confidentiality",
    title: "14. Confidentiality",
    content: [
      "14.1 Definition. \"Confidential Information\" means information disclosed by one party (\"Discloser\") to the other (\"Recipient\") that is marked or otherwise reasonably understood as confidential, including Customer Content, security documentation, product plans, and pricing. Confidential Information does not include information that is or becomes public without breach, was known to Recipient without duty of confidentiality, is independently developed, or is rightfully received from a third party.",
      "14.2 Protection. Recipient will use at least reasonable care to protect Confidential Information and use it only to fulfill obligations under this Agreement. Recipient may disclose Confidential Information to its employees, contractors, and Subprocessors who have a need to know and are bound by confidentiality obligations at least as protective as these Terms.",
      "14.3 Compelled Disclosure. Recipient may disclose Confidential Information if required by law, subpoena, or court order, provided it (if legally permitted) gives prompt notice and cooperates in seeking a protective order. Disclosures will be limited to the minimum required.",
    ],
  },
  {
    id: "indemnification",
    title: "15. Indemnification",
    content: [
      "15.1 By Teammato. We will defend Customer against any third-party claim alleging that the Services infringe a valid U.S. patent, copyright, or trademark, and pay damages finally awarded (or settlement amounts we approve). If the Services become the subject of an infringement claim, we may procure the right to continue using them, modify them to be non-infringing, or replace them with a functionally equivalent alternative. If none is commercially reasonable, we may terminate the affected Services and provide a pro-rata refund of prepaid, unused fees.",
      "Exclusions. We have no obligation for claims to the extent arising from: (a) Customer Content; (b) combinations with items not supplied by Teammato; (c) modifications not made by Teammato; or (d) use not in accordance with the Documentation.",
      "15.2 By Customer. Customer will defend Teammato against third-party claims arising from Customer Content, Customer's use of the Services in violation of these Terms or law, or Customer's combination of the Services with third-party products or services, and pay damages finally awarded (or settlements Customer approves).",
      "15.3 Procedure. The indemnified party must promptly notify the indemnifying party, provide reasonable cooperation, and allow sole control of the defense and settlement (provided settlement fully releases the indemnified party without admission of fault and does not impose obligations other than money damages).",
    ],
  },
  {
    id: "liability",
    title: "16. Limitation of Liability",
    content: [
      "TO THE MAXIMUM EXTENT PERMITTED BY LAW: (A) NEITHER PARTY WILL BE LIABLE FOR ANY INDIRECT, INCIDENTAL, SPECIAL, CONSEQUENTIAL, COVER, OR PUNITIVE DAMAGES, OR FOR ANY LOSS OF PROFITS, REVENUE, GOODWILL, OR DATA, ARISING OUT OF OR RELATED TO THIS AGREEMENT, EVEN IF ADVISED OF THE POSSIBILITY; AND (B) EACH PARTY'S TOTAL AGGREGATE LIABILITY FOR ALL CLAIMS IN THE AGGREGATE WILL NOT EXCEED THE AMOUNTS PAID OR PAYABLE BY CUSTOMER TO TEAMMATO FOR THE SERVICES GIVING RISE TO THE CLAIM DURING THE TWELVE (12) MONTHS IMMEDIATELY PRECEDING THE EVENT GIVING RISE TO LIABILITY.",
      "The limitations above do not apply to a party's indemnification obligations (Section 15.1 limited to replacement/refund remedy), infringement of the other party's IP rights, or breach of confidentiality (Section 14).",
    ],
  },
  {
    id: "termination",
    title: "17. Suspension; Term; Termination",
    content: [
      "17.1 Suspension. We may suspend access immediately if we reasonably believe: (a) there is a security risk to the Services or Customer Content; (b) Customer is in material breach (including non-payment); or (c) suspension is required by law. We will restore access when the issue is resolved.",
      "17.2 Term. This Agreement starts on the Effective Date of the initial Order and continues until all subscriptions under this Agreement have expired or been terminated.",
      "17.3 Termination for Cause. Either party may terminate this Agreement for material breach if the breach remains uncured thirty (30) days after written notice (ten (10) days for payment breaches).",
      "17.4 Effect of Termination. Upon termination, Customer will stop using the Services and pay all amounts due. We will delete or de-identify Customer Content per Section 12. Sections that by their nature should survive (including 4, 5, 6, 8, 9, 10, 11, 12, 13, 14–20) will survive.",
    ],
  },
  {
    id: "dispute-resolution",
    title: "18. Dispute Resolution; Governing Law; Arbitration",
    content: [
      "18.1 Governing Law. These Terms and any dispute arising out of or relating to them shall be governed by the laws in the state where Teammato LLC is currently incorporated, without regard to its conflict-of-laws rules.",
      "18.2 Informal Resolution. Before filing a claim, the parties agree to attempt to resolve the dispute informally for thirty (30) days by emailing Trust@teammato.com.",
      "18.3 Arbitration. If the dispute is not resolved, it shall be finally resolved by binding, individual arbitration administered by a reputable arbitration provider under its rules then in effect. The seat and venue shall be in the state where Teammato LLC is currently incorporated. Judgment on the award may be entered in any court of competent jurisdiction.",
      "18.4 Class Action Waiver. To the fullest extent permitted by law, disputes must be brought on an individual basis and not as a class, consolidated, or representative action.",
      "18.5 Injunctive Relief. Notwithstanding the foregoing, either party may seek temporary or preliminary injunctive relief in any court of competent jurisdiction to protect its rights pending arbitration.",
    ],
  },
  {
    id: "changes",
    title: "19. Changes to the Services or Terms",
    content: [
      "19.1 Changes to the Services. We may modify features (including Beta features) or discontinue components, provided we maintain materially similar core functionality during a paid term.",
      "19.2 Changes to Terms. We may update these Terms from time to time. If changes are material, we will provide notice (e.g., via Admin email or in-product notice). Updated Terms will apply on the next renewal or thirty (30) days after notice, whichever is earlier. Continued use after the effective date constitutes acceptance.",
    ],
  },
  {
    id: "notices",
    title: "20. Notices",
    content: [
      "Notices to Teammato must be sent to Trust@teammato.com (legal/security) or Contact@teammato.com (general). Notices to Customer may be sent to Admin email(s) or shown in-product. Electronic communications satisfy any legal requirement that communications be in writing.",
    ],
  },
  {
    id: "dmca",
    title: "21. DMCA and IP Complaints",
    content: [
      "If you believe your copyright has been infringed, send a notice including: (a) your signature; (b) identification of the copyrighted work; (c) identification of the allegedly infringing material; (d) your contact information; (e) a statement of good-faith belief; and (f) a statement under penalty of perjury regarding accuracy and authority, to Contact@teammato.com. We may remove or disable access to material alleged to infringe and, in appropriate circumstances, terminate repeat infringers.",
    ],
  },
  {
    id: "force-majeure",
    title: "22. Force Majeure",
    content: [
      "Neither party will be liable for delay or failure to perform due to events beyond its reasonable control, including acts of God, natural disasters, war, terrorism, labor disputes, governmental actions, utility failures, Internet disturbances not caused by the party, or third-party provider outages.",
    ],
  },
  {
    id: "assignment",
    title: "23. Assignment; Subcontracting",
    content: [
      "Neither party may assign this Agreement without the other party's prior written consent, except either party may assign without consent in connection with a merger, reorganization, or sale of substantially all assets, provided the assignee is not a direct competitor and assumes all obligations. Teammato may engage Subprocessors to perform the Services consistent with these Terms.",
    ],
  },
  {
    id: "entire-agreement",
    title: "24. Entire Agreement; Order of Precedence; Severability; Waiver",
    content: [
      "24.1 Entire Agreement. These Terms, the Order(s), the Privacy Policy, and any DPA constitute the entire agreement between the parties and supersede prior agreements relating to the Services.",
      "24.2 Order of Precedence. In the event of conflict: DPA (for processing of Personal Data in scope) controls over these Terms; then the Order; then these Terms; then the Documentation.",
      "24.3 Severability. If any provision is held unenforceable, it will be modified to the minimum extent necessary to make it enforceable, and the remaining provisions will remain in full force.",
      "24.4 Waiver. Failure to enforce any provision is not a waiver of future enforcement.",
    ],
  },
  {
    id: "government",
    title: "25. Government Users",
    content: [
      "The Services are \"commercial products\" and \"commercial computer software\" developed at private expense. Government users acquire rights only as set forth in these Terms.",
    ],
  },
  {
    id: "contact",
    title: "26. Contact",
    content: [
      "Legal & Security: Trust@teammato.com",
      "General & Support: Contact@teammato.com",
      "By using the Services, you acknowledge that you have read and agree to these Terms.",
    ],
  },
];

export default function Terms() {
  const introduction = `These Terms of Service (the "Terms" or this "Agreement") govern access to and use of Teammato, LLC's ("Teammato," "we," "us," or "our") websites, admin console, APIs, Slack applications, and related services (collectively, the "Services"). By creating an account, installing or authorizing our Slack app, or otherwise using the Services, you agree to these Terms. If you are entering into this Agreement on behalf of an entity, you represent that you have authority to bind that entity. If you do not agree, do not use the Services. For privacy specifics, see our Privacy Policy. Enterprise customers may request a Data Processing Addendum ("DPA") by emailing Trust@teammato.com.`;
  
  return (
    <LegalDocument
      title="Teammato Terms of Service"
      effectiveDate="October 6, 2025"
      introduction={introduction}
      sections={termsSections}
      downloadFilename="teammato-terms-of-service.txt"
    />
  );
}
